version: '3.8'

services:
    front-end-test:
        container_name: front-end-test
        image: front-end-test
        build:
            context: ./app/front-end
            dockerfile: Dockerfile
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env
        volumes:
            - ./app/front-end/src:/front-end/src
            - ./app/front-end/public:/front-end/public
