version: '3.8'

services:
    back-end:
        container_name: back-end
        image: back-end:42
        build: 
            context: ./app/back-end
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - data-base
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./app/back-end:/back-end
            - v_data-base:/var/lib/postgresql/data
        networks:
            - ft_transcendence

    front-end:
        container_name: front-end
        image: front-end:42
        build: 
            context: ./app/front-end
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - back-end
        ports:
            - "3000:3000"
        env_file:
            - .env
        volumes:
            - ./app/front-end:/front-end
            - /front-end/node_modules
            - /front-end/.next

        networks:
            - ft_transcendence
    
    data-base:
        container_name: data-base
        image: data-base:42
        build: 
            context: ./app/data-base
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - v_data-base:/var/lib/postgresql/data
        networks:
            - ft_transcendence
    
    redis:
        container_name: redis
        image: redis:42
        build: 
            context: ./services/redis
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - back-end
        ports:
            - "6379:6379"
        env_file:
            - .env
        networks:
            - ft_transcendence

volumes:
    v_data-base:
        name: v_data-base
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /Users/${USER}/Desktop/data

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge