version: '3.8'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
            - ./prometheus/data:/prometheus
        ports:
            - '9090:9090'
        networks:
            - net

    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_SERVER_HTTP_PORT=3002
            - GF_SECURITY_ADMIN_USER=admin
            - GF_AUTH_BASIC_ENABLED=true
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/data:/var/lib/grafana
        env_file:
            - .env
        ports:
            - '3002:3002'
        networks:
            - net

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        restart: unless-stopped
        user: root
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
            - ./exporters/node_exporter/node_exporter.yml:/etc/node_exporter/node_exporter.yml:ro
        ports:
            - 9100:9100
        networks:
            - net

networks:
    net:
        driver: bridge
