version: '3.8'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
        ports:
            - '9090:9090'
        networks:
            - net

    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_SERVER_HTTP_PORT=3002
            - GF_SECURITY_ADMIN_USER=admin
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        env_file:
            - .env
        ports:
            - '3002:3002'
        networks:
            - net

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        restart: unless-stopped
        user: root
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        ports:
            - 9100:9100
        networks:
            - net

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        restart: unless-stopped
        volumes:
            - /:/rootfs:ro
            - /sys:/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080
        privileged: true
        networks:
            - net

networks:
    net:
        driver: bridge
