name: TypeScript and Prettier Check

on: [push, pull_request]

jobs:
  typescript-prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd app/front-end/
          npm install

      - name: Run TypeScript Check
        run: |
          cd app/front-end/
          npm run tsc
          if [ $? -ne 0 ]; then
            echo "TypeScript check failed. Aborting push."
            exit 1
          else
            echo "TypeScript check passed."
          fi

      - name: Run Prettier Check
        run: |
          cd app/front-end/
          npm run format
          npm run format:check
          if [ $? -ne 0 ]; then
            echo "Prettier check failed. Aborting push."
            exit 1
          else
            echo "Prettier check passed."
          fi

      - name: Commit and Push Changes
        if: failure()
        run: |
          git config --global user.email "ael-mouz@student.1337.ma"
          git config --global user.name "ael-mouz"
          git checkout -B ${{ github.ref_name }}
          git add .
          git commit -m "[Style] TypeScript and Prettier fixes"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
