name: Django Tests

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true
      - run: docker-compose --version

      - name: Set up Docker Compose
        run: |
          pip install docker
          pip install docker-compose

      - name: Build and run tests
        run: |
          make build
          docker-compose run --rm back-end python manage.py test

      - name: Tear down
        if: ${{ always() }}
        run: docker-compose down