name: Django Tests

# on:
#   push:
#     branches: [main]

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: docker-compose -f docker-compose.yml exec back-end python manage.py test

      - name: Tear down
        if: ${{ always() }}
        run: docker-compose -f docker-compose.yml down
