name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cp app/back-end/requirements.txt .
        pip install -r requirements.txt
        pip install pylint pylint-django
    - name: Analysing the code with pylint
      run: |
        cp app/back-end/.pylintrc .
        pylint $(git ls-files '*.py') --rcfile=.pylintrc --django-settings=ft_transcendence.settings
